version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 10s
      retries: 5

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: example
      DB_PASSWORD: example
      DB_NAME: example
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: npm run build && npm run start

volumes:
  db_data:
