INSERT INTO users (name, email, created_at, updated_at) VALUES 
('User1', 'user1@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User2', 'user2@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User3', 'user3@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User4', 'user4@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User5', 'user5@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User6', 'user6@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User7', 'user7@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User8', 'user8@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User9', 'user9@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('User10', 'user10@example.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO songs (name, created_at, updated_at) VALUES 
('Song1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Song20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE songs SET name = 'Unknown' WHERE name IS NULL;

ALTER TABLE songs ALTER COLUMN name SET NOT NULL;


-- Assign each user 3 songs they like
INSERT INTO user_songs (user_id, song_id) VALUES 
(1, 1), (1, 2), (1, 3),
(2, 4), (2, 5), (2, 6),
(3, 7), (3, 8), (3, 9),
(4, 10), (4, 11), (4, 12),
(5, 13), (5, 14), (5, 15),
(6, 16), (6, 17), (6, 18),
(7, 19), (7, 20), (7, 1),
(8, 2), (8, 3), (8, 4),
(9, 5), (9, 6), (9, 7),
(10, 8), (10, 9), (10, 10)
ON CONFLICT (user_id, song_id) DO NOTHING;

